// Auto-generated by esp-rpc generator - do not edit

import { BufferWriter, BufferReader } from './binary';

export const UserStatus = {
  ACTIVE: 1,
  INACTIVE: 2,
  DELETED: 3,
} as const;
export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus];

export interface User {
  id: number;
  name: string;
  email?: string | undefined;
  status: UserStatus;
}

export interface CreateUserRequest {
  name: string;
  email?: string | undefined;
  password?: string | undefined;
}

export interface UserResponse {
  id: number;
  name: string;
  email: string;
  status: UserStatus;
}

export function writeUser(w: BufferWriter, v: User): void {
  w.writeI32(v.id);
  w.writeStr(v.name);
  w.writeBool(v.email !== undefined);
  if (v.email !== undefined) {
    w.writeStr(v.email);  }
  w.writeI32(v.status);
}

export function readUser(r: BufferReader): User {
  return {
    id:     r.readI32(),
    name:     r.readStr(),
    email:     r.readBool() ? (r.readStr()) : undefined,
    status:     r.readI32() as UserStatus,
  };
}

export function writeCreateUserRequest(w: BufferWriter, v: CreateUserRequest): void {
  w.writeStr(v.name);
  w.writeBool(v.email !== undefined);
  if (v.email !== undefined) {
    w.writeStr(v.email);  }
  w.writeBool(v.password !== undefined);
  if (v.password !== undefined) {
    w.writeStr(v.password);  }
}

export function readCreateUserRequest(r: BufferReader): CreateUserRequest {
  return {
    name:     r.readStr(),
    email:     r.readBool() ? (r.readStr()) : undefined,
    password:     r.readBool() ? (r.readStr()) : undefined,
  };
}

export function writeUserResponse(w: BufferWriter, v: UserResponse): void {
  w.writeI32(v.id);
  w.writeStr(v.name);
  w.writeStr(v.email);
  w.writeI32(v.status);
}

export function readUserResponse(r: BufferReader): UserResponse {
  return {
    id:     r.readI32(),
    name:     r.readStr(),
    email:     r.readStr(),
    status:     r.readI32() as UserStatus,
  };
}

